# Generated by Django 3.1.7 on 2022-05-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_eircode',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
