# Generated by Django 3.1.7 on 2022-05-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20210314_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='eircode',
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
